-- Query 1A
SELECT 
    E.F_NAME, E.L_NAME, JH.START_DATE
FROM
    EMPLOYEES E
        INNER JOIN
    JOB_HISTORY JH ON E.JOB_ID = JH.JOBS_ID
WHERE
    E.DEP_ID = 5;
    
-- Query 1B
SELECT 
    E.F_NAME, E.L_NAME, JH.START_DATE, J.JOB_TITLE
FROM
    EMPLOYEES E
        INNER JOIN
    JOB_HISTORY JH ON E.JOB_ID = JH.JOBS_ID
		INNER JOIN
	JOBS J ON JH.JOBS_ID = J.JOB_IDENT
WHERE
    E.DEP_ID = 5;

-- Query 2A
SELECT 
    E.EMP_ID, E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME
FROM
    EMPLOYEES E
        LEFT JOIN
    DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP;
    
-- Query 2B
SELECT 
    E.EMP_ID, E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME
FROM
    EMPLOYEES E
        LEFT JOIN
    DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP
WHERE
    E.B_DATE < '1980-01-01';
    
-- Query 2C
SELECT 
    E.EMP_ID, E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME
FROM
    EMPLOYEES E
        LEFT JOIN
    DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP
        AND E.B_DATE < '1980-01-01';

-- Query 3A
SELECT 
    E.F_NAME, E.L_NAME, D.DEP_NAME
FROM
    EMPLOYEES E
        LEFT JOIN
    DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP;
	