-- Query #1
SELECT 
    *
FROM
    EMPLOYEES
WHERE
    EMPLOYEES.ADDRESS LIKE '%Elgin,IL';

-- Query #2
SELECT 
    *
FROM
    EMPLOYEES
WHERE
    B_DATE BETWEEN '1970-01-01' AND '1979-12-31';

-- Query #3
SELECT 
    *
FROM
    EMPLOYEES
WHERE
    DEP_ID = 5
        AND SALARY BETWEEN 60000 AND 70000;
        
-- Query 4A
SELECT 
    *
FROM
    EMPLOYEES
ORDER BY DEP_ID;

-- Query 4B
SELECT 
    *
FROM
    EMPLOYEES
ORDER BY DEP_ID DESC , L_NAME DESC;

-- Query 5A
SELECT 
    DEP_ID, COUNT(*) AS 'Total Employees'
FROM
    EMPLOYEES
GROUP BY DEP_ID;

-- Query 5B
SELECT 
    DEP_ID,
    COUNT(*) AS 'Total Employees',
    FORMAT(AVG(SALARY), 2) AS 'Avg Salary'
FROM
    EMPLOYEES
GROUP BY DEP_ID;

-- Query 5C
SELECT 
    DEP_ID,
    COUNT(*) AS 'NUM_EMPLOYEES',
    FORMAT(AVG(SALARY), 2) AS 'AVG_SALARY'
FROM
    EMPLOYEES
GROUP BY DEP_ID;

-- Query 5D
SELECT 
    DEP_ID,
    COUNT(*) AS 'NUM_EMPLOYEES',
    FORMAT(AVG(SALARY), 2) AS 'AVG_SALARY'
FROM
    EMPLOYEES
GROUP BY DEP_ID
ORDER BY 3;

-- Query 5E
SELECT 
    DEP_ID,
    COUNT(*) AS 'NUM_EMPLOYEES',
    FORMAT(AVG(SALARY), 2) AS 'AVG_SALARY'
FROM
    EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY 3;

-- Query 6
SELECT 
    EMPLOYEES.*, DEPARTMENTS.DEP_NAME
FROM
    EMPLOYEES,
    DEPARTMENTS
WHERE
    EMPLOYEES.DEP_ID = DEPARTMENTS.DEPT_ID_DEP
ORDER BY DEP_NAME, L_NAME DESC;
